#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: TinyActive - Base On HOSTVN.VN Scripts      #
#                  Website: https://github.com/TinyActive/panel      #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/tinycp/menu/validate/rule
source /var/tinycp/menu/helpers/function

_update(){
    _cd_dir "${DEFAULT_DIR_TOOL}"
    rm -rf ./memcached
    git clone https://github.com/elijaa/phpmemcachedadmin.git
    rm -rf "${DEFAULT_DIR_TOOL}"/phpmemcachedadmin/docker
    mv phpmemcachedadmin memcached
    chown -R nginx:nginx "${DEFAULT_DIR_TOOL}"/memcached
    clear
    printf "%s\n" "${GREEN}Update Memcached Dashboard success.${NC}"
}

_update
menu_admin_tool
