#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: TinyActive - Base On HOSTVN.VN Scripts      #
#                  Website: https://github.com/TinyActive/panel      #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# set evironment variables in /etc/environment
if [[ -f /etc/environment ]]; then
    echo "HOME_PAGE=https://tinyactive.github.io/panel" > /etc/environment
    export $(grep -v '^#' /etc/environment | xargs)
 else
    echo "HOME_PAGE=https://tinyactive.github.io/panel" > /etc/environment
    export $(grep -v '^#' /etc/environment | xargs)
fi


# Check if the script is run as root
if [[ "$(id -u)" != "0" ]]; then
    echo "This script must be run as root. Please use 'sudo' or switch to the root user."
    exit 1
fi

#check evironment variables 
if [[ -z "${HOME_PAGE}" ]]; then    
    echo "HOME_PAGE variable is not set. creat issue github report bug with info os."
    echo ${date +%Y-%m-%d %H:%M:%S}
    echo $(cat /etc/os-release)
    echo $(uname -a)
    exit 1
fi


# Remove old install folder
rm -rf install

# Set Color
RED='\033[0;31m'
NC='\033[0m'

OS=$(grep -oP '(?<=^ID=).+' /etc/os-release | tr -d '"')

SCRIPT_LINK="${HOME_PAGE}/${OS}"
OS_LIST="ubuntu debian"
RAM_TOTAL=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
LOW_RAM='400000'

# Set Lang
ROOT_ERR="Ban can dang nhap SSH voi user root."
CANCEL_INSTALL="Huy cai dat..."
RAM_NOT_ENOUGH="Canh bao: Dung luong RAM qua thap de cai Script. (It nhat 512MB)"
WRONG_OS="Rat tiec he dieu hanh ban dang su dung khong duoc ho tro."

export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

if [[ "$(id -u)" != "0" ]]; then
    printf "${RED}%s${NC}\n" "${ROOT_ERR}"
    printf "${RED}%s${NC}\n" "${CANCEL_INSTALL}"
    exit
fi

if [[ ${RAM_TOTAL} -lt ${LOW_RAM} ]]; then
    printf "${RED}%s${NC}\n" "${RAM_NOT_ENOUGH}"
    printf "${RED}%s${NC}\n" "${CANCEL_INSTALL}"
    exit
fi

## check service
if systemctl is-active --quiet apache2; then
    printf "%s\n" "${RED}Apache process detected, exit...${NC}"
    exit
fi
if systemctl is-active --quiet mysqld; then
    printf "%s\n" "${RED}Mysql process detected, exit...${NC}"
    exit
fi
if systemctl is-active --quiet mariadb; then
    printf "%s\n" "${RED}Mysql process detected, exit...${NC}"
    exit
fi
if systemctl is-active --quiet mysql; then
    printf "%s\n" "${RED}Mysql process detected, exit...${NC}"
    exit
fi
if systemctl is-active --quiet nginx; then
    printf "%s\n" "${RED}Nginx process detected, exit...${NC}"
    exit
fi

# kiểm tra hệ điều hành chỉ hỗ trợ ubuntu, debian không hỗ trợ centos, almalinux hay các hệ điều hành khác
OS_LIST=("ubuntu" "debian")
WRONG_OS="Rat tiec he dieu hanh ban dang su dung khong duoc ho tro."
if [[ "${OS}" == "debian" ]]; then
    OS="debian"
elif
    [[ "${OS}" == "ubuntu" ]]; then
    OS="ubuntu"
else
    OS="unknown"
    printf "${RED}%s${NC}\n" "${WRONG_OS}"
fi

#wellcome message  
welcome() {
    clear
    echo "#############################################"
    echo "#                                           #"
    echo "#       Auto Install & Optimize LEMP       #"
    echo "#                                           #"
    echo "#           Author: TinyPanel - HOSTVN Base #"
    echo "#             Website: tinyactive.net       #"
    echo "#                                           #"
    echo "#############################################"
}




if [[ " ${OS_LIST[*]} " == *" ${OS} "* ]]; then
    if [[ "${OS}" == "centos" || "${OS}" == "almalinux" ]]; then
        yum -y install dos2unix
    else
        apt -y install dos2unix
    fi
    curl -sO "${SCRIPT_LINK}"
    dos2unix "${OS}"
    chmod +x "${OS}"
    bash "${OS}"
else
    printf "${RED}%s${NC}\n" "${WRONG_OS}"
    printf "${RED}%s${NC}\n" "${CANCEL_INSTALL}"
    exit
fi
